<div class="video-gallery-container">

    <?php $data = $this->getAllData(); ?>

    <u><h1><?php echo $this->getTitle() ?></h1></u>
    <p><?php echo $this->getDescription() ?></p>

    <?php if (count($data) == 0): ?>
        <h2><b><?php echo $this->__('There are no videos availble into the gallery at the moment.') ?><b></h2>
    <?php endif; ?>

    <div class="gallery-slider-main">
        <?php foreach ($data as $key => $value): ?>
            <?php
            $urlKey = explode('?v=', $value->getVideogalleryUrl());
            $videoSrc = "http://www.youtube-nocookie.com/embed/" . $urlKey[1] . "?wmode=opaque&rel=0&autohide=1&showinfo=0&autoplay=0";
            ?>
            <div class="video-frame">
                <iframe id="iframe-<?php echo $key; ?>"
                        width="<?php echo $this->getWidth(); ?>"
                        height="<?php echo $this->getHeight(); ?>"
                        src="<?php echo $videoSrc; ?>"
                        frameborder="0" allowfullscreen></iframe>
                <h3><?php echo $value->getName() ?></h3>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<script type="text/javascript">
    jQuery(document).ready(function (e) {
        jQuery('.gallery-slider-main').slick({
            dots: true,
            infinite: true,
            cssEase: 'linear'
        });
    });
</script>