<?php if (Mage::helper('videogallery')->checkEnableDisable()): ?>
    <div style="text-align: center">
        <?php $data = $this->getAllData(); ?>

        <u><h1 style="text-align: left"><?php echo $this->getTitle() ?></h1></u>
        <p style="text-align: left"><?php echo $this->getDescription() ?></p>

        <?php if (count($data) == 0): ?>
            <h2><b><?php echo $this->__('There are no videos availble into the gallery at the moment.') ?><b></h2>
        <?php else: ?>
            <?php $firstItemUrlKey = $data->getFirstItem()->getVideogalleryUrl(); ?>
            <div id="main_div_video_frame">
                <iframe id="videoframe" width="<?php echo $this->getWidth(); ?>"
                        height="<?php echo $this->getHeight(); ?>"
                        src="http://www.youtube-nocookie.com/embed/<?php echo $firstItemUrlKey[1]; ?>?wmode=opaque&rel=0&autohide=1&showinfo=0&autoplay=0"
                        frameborder="0" allowfullscreen></iframe>
            </div>
            <?php
            foreach ($data as $key => $result):
                $url_key = explode('?v=', $result->getVideogalleryUrl());
                ?>

                <div style="float: left;margin: 5px 10px 5px 5px;width: 285px;position: relative;">
                    <a style="text-decoration:none;" href="#" onclick="selectvideo('<?php echo $url_key[1]; ?>');"> <img
                                src="http://tafelzeil.heliossolutions.in/skin/frontend/default/tafelzeil/images/youtube.png"
                                alt="" style="position: absolute;top: 100px;left: 125px;"><img
                                src="http://img.youtube.com/vi/<?php echo $url_key[1] ?>/0.jpg" width="285px">
                        <p style="text-align: justify;margin-top: 5px; "> <?php echo $result->getName(); ?></p></a>
                </div>
            <?php
            endforeach;
        endif;
        ?>
    </div>
<?php else: ?>
    <h2 style="border: 2px solid #000"><?php echo $this->__('This Extension is Currently Disable so, It will be redirected to our homepage in 5 seconds.') ?></h2>
    <script type="text/javascript">
        //<![CDATA[
        setTimeout(function () {
            location.href = '<?php echo $this->getUrl('') ?>'
        }, 5000);
        //]]>
    </script>
<?php
endif; ?>